USE [master]
GO

/****** Object:  Database [PostavkiTovar]    Script Date: 07.02.2023 15:50:47 ******/
CREATE DATABASE [PostavkiTovar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PostavkiTovar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PostavkiTovar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PostavkiTovar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PostavkiTovar_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PostavkiTovar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PostavkiTovar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PostavkiTovar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PostavkiTovar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PostavkiTovar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PostavkiTovar] SET ARITHABORT OFF 
GO

ALTER DATABASE [PostavkiTovar] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PostavkiTovar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PostavkiTovar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PostavkiTovar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PostavkiTovar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PostavkiTovar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PostavkiTovar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PostavkiTovar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PostavkiTovar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PostavkiTovar] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PostavkiTovar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PostavkiTovar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PostavkiTovar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PostavkiTovar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PostavkiTovar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PostavkiTovar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PostavkiTovar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PostavkiTovar] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PostavkiTovar] SET  MULTI_USER 
GO

ALTER DATABASE [PostavkiTovar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PostavkiTovar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PostavkiTovar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PostavkiTovar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PostavkiTovar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PostavkiTovar] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PostavkiTovar] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PostavkiTovar] SET  READ_WRITE 
GO

