USE [master]
GO
CREATE LOGIN [user1] WITH PASSWORD=N'123456' MUST_CHANGE,
DEFAULT_DATABASE=[master], check_expiration=on , CHECK_POLICY=ON
GO
ALTER SERVER ROLE [dbcreater] ADD MEMBER [user1]
GO
DENY VIEW ANY DATABASE TO [user1]
GO
GRANT ALTER ANY DATABESE TO [user1]
GO
USE [master]
GO
DENY ALTER ON DATABASE ::[master] TO [user1]
GO